### ISSUE TITLE
Videos stop frequently without an apparent reason

### ISSUE THREAD

**Issue by yurivict** [flaviotordini/minitube#211] opened 2021-09-21 19:15 UTC
Version: 3.9.1 install from a package.

FreeBSD 13

**Comment by therealgoodstuff** [comment] 2021-10-05 09:50
Same issue with Windows 10 here.
But was the issue with the former version too so nothing new.
Video starts or does not, if it starts there is a good chance that it plays stop and go.
You have to try again until it finally works for that video. The next video may or may not have that
issue again. Please fix that. The program is broken af for a long time now. Thx!

**Comment by alium** [comment] 2021-10-16 11:03
my problem is fixed now. thanks!

**Comment by yurivict** [comment] 2021-10-16 15:59
The source code didn't change after 3.9.1. Where is the fix then?

**Comment by therealgoodstuff** [comment] 2021-10-16 22:27
after almost a year the issue seems to be gone now. Thx Flavio! 

@yuri : does that really  matter ? all I care for is that it works now :D

**Comment by yurivict** [comment] 2021-10-16 22:30
> after almost a year the issue seems to be gone now. Thx Flavio!

```3.9.1```, the latest version, still has this problem.

**Comment by therealgoodstuff** [comment] 2021-10-17 06:48
not for me anymore. maybe the issue is connected to something else ? internet connection ? using a vpn perhaps ? antivirus?

**Comment by yurivict** [comment] 2021-10-17 07:09
No VPN, no antivirus. internet is stable.

**Comment by alepez** [comment] 2022-09-09 08:27
I have this problem too. 1sec play, 3sec pause, repeat. Each time it starts again, this error appears in the terminal:

```
Error disabling idle display sleep "The name org.freedesktop.ScreenSaver was not provided by any .service files"
```

**Comment by alepez** [comment] 2022-09-09 09:09
The dbus error is not the cause, it is an effect of pause.

**Comment by flaviotordini** [comment] 2022-09-24 07:28
Should be fixed now.

**Closed by flaviotordini** 2022-09-24 07:28 UTC

**Comment by yurivict** [comment] 2022-09-24 15:08
Could you please make a release with the fix?

**Comment by alepez** [comment] 2022-09-28 12:00
> Should be fixed now.

19 days ago I tested with version 84cc258 and the behavior was: 1sec play, 3sec pause, repeat.

**Comment by alepez** [comment] 2022-09-28 12:06
I cannot reproduce the problem. Maybe an update of some dependency has fixed it. But I'm sure I tested with the last git version, because I added some log message to better understand the issue and the code is still in my pc.
