### ISSUE TITLE
Minitube-3.6.2 to 3.6.5 distort video and freezes desktop running with Linux-5.8.17

### ISSUE THREAD

**Issue by Ulenrich** [flaviotordini/minitube#177] opened 2020-10-29 20:08 UTC
I tried 3 times. Two times I had to hard stop using the power line to end the computer working. Last time I quickly got out of my desktop and could start a root console: Somehow mpv does hang only to stop with sigterm ill. My environment runs minitube well with version Minitube-3.4

What can I do to help find the error? I am on Gentoo and compile myself the whole system. So I can do patches ...

**Comment by Ulenrich** [comment] 2020-10-29 20:14
Forgot to tell: I am using Gentoo default version of qt-5.15.1 on X-server not Wayland. The video viewer Mpv-0.32.0 works fine. Why is this viewer distorting the videos when runnig under Minitube ???

**Comment by thewolfwillcome** [comment] 2020-11-28 20:20
I cannot reproduce it here.
I also use gentoo running kernel 5.8.18 and qt 5.15.1-r1 on X11.
AFAIK minitube configures mpv to try to use hw accelerated video decoding.
On my system with a AMD Radeon RX 590 mpv uses vaapi to decode h264 encoded content.
Maybe your system has a problem with that. Hard freezes of the system is mostly a symptom of an hardware problem.

**Comment by Ulenrich** [comment] 2020-11-29 23:22
>Hard freezes of the system is mostly a symptom of an hardware problem.
Yes, therefore I don't grasp my bug: The same mpv-0.32.0 (now updated mpv-0.33.0) worked for minitub-3.4 but now freezes my system.  That is my desperation about it.

But I remember having had a problem years ago with vdpau with my nvidia graphics. I have a look and see on my system this flag:
mpv : -vdpau
ffmpeg : vdpau 
Maybe minitube-3.6 calls ffmpeg directly now? 
So, I'll give it a try again without vdpau ....

@thewolfwillcome very thnx for the inspiration !

**Comment by flaviotordini** [comment] 2020-11-30 09:25
I think this is out of scope for Minitube, especially on Linux where you MPV version may change. I'm closing this. I cannot help in any way. If you want to experiment, Minitube uses its own mpv wrapper: https://github.com/flaviotordini/media

**Closed by flaviotordini** 2020-11-30 09:25 UTC

**Comment by Ulenrich** [comment] 2020-12-01 14:04
I think I got the error on my system:
I had an install of qtav on my system.
Arrrgh ...
