### ISSUE TITLE
Sound sometimes doesn't work

### ISSUE THREAD

**Issue by pomputer** [flaviotordini/minitube#155] opened 2020-02-08 11:15 UTC
Sometimes when I play a video it doesn't have sound, but if I click on another video and then click back to the first video there is sound. Do you know what could be causing this?
Thanks!

**Comment by Kieltux** [comment] 2020-03-12 17:48
Same here with minitube 3.3.

**Comment by benchile55** [comment] 2020-04-27 02:20
same here running latest mpv and minitube 3.3 from Manjaro Linux repos. I cannot get audio  just watch video. I have a mute minitube 3.3. It also sometimes skips some videos, moves fast to next in the playlist. 
https://i.imgur.com/2GaHUcH.png

**Comment by flaviotordini** [comment] 2020-04-27 16:35
I believe this is an MPV bug. Couldn't replicate it on the Mac.

**Comment by vitovt** [comment] 2020-05-21 22:26
>Sometimes I cannot get audio just watch video. I have a mute minitube 3.3. It also sometimes skips some videos, moves fast to next in the playlist.

Sabe behaviour. Ubuntu 18.04

**Comment by thewolfwillcome** [comment] 2020-06-02 19:48
This seems to be a timing problem when playing video and audio as separate files. It seems that adding an audio file/stream while the main file (video) isn't yet loaded the audio-add command will fail.

After adding an sleep(1) between the loadfile and audio-add command the audio playback works everytime.

But this seemed to be an hack to me so I changed the code so that the audio file is added after mpv emits the event "file loaded".

Attach a patch file for my changes
[fix_audio_playback.patch.txt](https://github.com/flaviotordini/minitube/files/4719336/fix_audio_playback.patch.txt)

**Comment by Kieltux** [comment] 2020-06-04 16:44
@thewolfwillcome: I am one of the minitube maintainer for openSUSE.
I applied your patch to my private build on OBS (https://build.opensuse.org/package/show/home:Kieltux:tools/minitube) and your patch fix the problem with the missing sound for me.
Thank you.

**Comment by santiyounger** [comment] 2020-06-07 18:33
Hey, guys I have the exact same problem audio just randomly stops working. I'm using Linux Manjaro KDE Plasma, installed it from Pamac software installer, then added an API  and it all works except for the audio.

I'd be happy to try the patch that @Kieltux and @thewolfwillcome  mentioned, but  I have no idea how to do that, (still new to Linux) would love some instructions if possible.

Thanks

**Comment by flaviotordini** [comment] 2020-06-07 19:51
@thewolfwillcome thanks for the patch. Unfortunate timing because I just released 3.4. I will do a minor release for this after I test it.

I have to say that this missing sound bug is not happening anymore on my Linux box. I've seen in the past but cannot reproduce it anymore. Maybe it's related to the MPV version?

**Comment by thewolfwillcome** [comment] 2020-06-07 20:55
For easier integration I created a pull request :)
https://github.com/flaviotordini/media/pull/3

**Comment by flaviotordini** [comment] 2020-06-11 15:22
Ok fixed in 3.4.2

**Closed by flaviotordini** 2020-06-11 15:22 UTC

**Comment by nasserbinlaboun** [comment] 2020-06-13 22:31
Same issue with version 3.4.2
